### ISSUE TITLE
Migrate to new architecture

### ISSUE THREAD

**Issue by finnp** [hoodiehq/hoodie-account-server#130]
part of https://github.com/hoodiehq/hoodie/issues/458

- [x] rename to `hoodie-account-server`
- [x] in `package.json`, set `"name"` to `"@hoodie/account-server"`, and add `"publishConfig": {"access": "public"}`
- [x] find `hoodie-account-server` and replace with `hoodie-account-server`
- [x] do commits as in https://github.com/hoodiehq/hoodie-log/issues/31

Once merged

- [x] deprecate `hoodie-server-account` in the npm registry
- [ ] ~~enable coveralls for new repo name (run `COVERALLS_REPO_TOKEN=... npm run coverage`, then on coveralls.io require `100%` coverage for success)~~ Coverage is disabled, see https://github.com/hoodiehq/hoodie-account-server/issues/37
- [ ] ~~update branch protection: re-enable coveralls~~ Coverage is disabled, see https://github.com/hoodiehq/hoodie-account-server/issues/37

/cc @gr2m

**Comment by gr2m** [comment]
all done, Coverage is disabled (https://github.com/hoodiehq/hoodie-account-server/issues/37), we can do that parts later
